version: "3.7"

services:
  postgres:
    container_name: koa_health-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: koa_health_user_activity_manager,koa_health_user_activity_manager-test
      PGDATA: /.data/postgres
    volumes:
      - postgres:/.data/postgres
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5440:5440"
    command: "-p 5440"
    networks:
      - postgres

  pgadmin:
    container_name: koa_health_pg-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin:/.data/pgadmin
    ports:
      - "53610:53610"
      - "80:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
